### ISSUE TITLE
BUG - comments user load

### ISSUE THREAD

**Issue by B3zo0** [SenseNet/sn-preview#14]
User load fails with access denied  when trying to see comments with alba
<details>
<summary>Exception</summary>
<pre>
Timestamp: 4/9/2019 11:45:18 AM
Message: Access denied.
Category: General
Priority: -1
EventId: 40
Severity: Warning
Title: 
Machine: SNSANDBOX01
Application Domain: IIS APPPOOL
Process Id: 11016
Process Name: w3wp
Managed Thread Id: 33
Thread Name: 
Extended Properties: Messages - ODataException: Access denied.

### Inner Exception:

SenseNetSecurityException: Access denied.
   at SenseNet.ContentRepository.Storage.Node.GetUserAccessLevel(NodeHead head)
   at SenseNet.ContentRepository.Storage.Node.LoadNode(NodeHead head, VersionNumber version)
   at SenseNet.ContentRepository.User.Load(String domain, String name, ExecutionHint hint)
   at SenseNet.ContentRepository.User.Load(String domainUserName)
   at SenseNet.Preview.Controller.PreviewComment..ctor(PreviewCommentData data)
   at SenseNet.Preview.Controller.PreviewCommentActions.<>c.<GetPreviewComments>b__2_0(PreviewCommentData cd)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at SenseNet.Portal.OData.ODataFormatter.ProcessOperationResponse(Object response, ODataRequest odataReq, Int32& count) in E:\BuildAgent\_work\63\s\src\Services\OData\ODataFormatter.cs:line 532
   at SenseNet.Portal.OData.ODataFormatter.WriteOperationResult(PortalContext portalContext, ODataRequest odataReq) in E:\BuildAgent\_work\63\s\src\Services\OData\ODataFormatter.cs:line 441
   at SenseNet.Portal.OData.ODataFormatter.WriteContentProperty(String path, String propertyName, Boolean rawValue, PortalContext portalContext, ODataRequest req) in E:\BuildAgent\_work\63\s\src\Services\OData\ODataFormatter.cs:line 353
   at SenseNet.Portal.OData.ODataHandler.ProcessRequest(HttpContext context, String httpMethod, Stream inputStream) in E:\BuildAgent\_work\63\s\src\Services\OData\ODataHandler.cs:line 134

---

ODataException/SenseNetSecurityException/FormattedMessage - Access denied. Path: /Root/IMS/BuiltIn/Portal/Admin PermissionType: See User: Public\alba@sensenet.com UserId: 4803
ODataException/SenseNetSecurityException/EventId - 40
ODataException/SenseNetSecurityException/Message - Access denied.
ODataException/SenseNetSecurityException/Path - /Root/IMS/BuiltIn/Portal/Admin
ODataException/SenseNetSecurityException/PermissionType - See
ODataException/SenseNetSecurityException/User - Public\alba@sensenet.com
UserName - Public\alba@sensenet.com
WorkingMode - 
IsHttpContext - yes
Url - https://devservice.demo.sensenet.com/odata.svc/Root/Sites/Default_Site/workspaces/Document/londondocumentworkspace/Document_Library('doc_20190313113826.pdf')/GetPreviewComments?page=1
Referrer - http://localhost:57035/iframe.html?id=documentviewer--showcase-app
</pre>
</details>

[code that fails](https://github.com/SenseNet/sn-preview/blob/b833224e561a661557e91bb5e02ef53f2a0147c5/src/Preview/Preview.Controller/PreviewCommentData.cs#L67)

related issue https://github.com/SenseNet/sn-client/issues/157

**Comment by B3zo0** [comment]
LGTM 👍
